### ISSUE TITLE
Fix issue with some calculation resulting to NaN

### ISSUE THREAD

**Issue by herico** [AnjaRL/frontend-mentor#3]
The following 2+.= results to NaN because of the dot. Maybe you should check what was the previous character before appending the dot, for example if the previous character was an operator then instead of just appending a dot(.) you should append zero and dot(0.) this ways it will not give you NaN
![image](https://user-images.githubusercontent.com/14878731/153291183-f9009ef4-3cc9-4dab-905e-5f6958a39cc8.png)

**Comment by AnjaRL** [comment]
Ok fixed
